### ISSUE TITLE
Bug in a dialog's viewpager

### ISSUE THREAD

**Issue by shmakova** [KeepSafe/TapTargetView#119]
Hi!
I have created ViewPager with FragmentPagerAdapter and put it into DialogFragment.
TapTargetView I initialize in the first ViewPager's fragment like this:
```
@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        TapTargetView.showFor(((DialogFragment) getParentFragment()).getDialog(),
                TapTarget.forView(demoView, getString(R.string.text_1))
                        .outerCircleColor(R.color.color_accent)
                        .targetCircleColor(R.color.color_primary)
                        .titleTextSize(20)
                        .textColor(R.color.white)
                        .dimColor(R.color.black)
                        .tintTarget(false)
                        .drawShadow(true)
                        .cancelable(false)
                        .transparentTarget(true)
                        .targetRadius(60),
                new TapTargetView.Listener() {
                    @Override
                    public void onTargetClick(TapTargetView view) {
                        super.onTargetClick(view);
                        targetClickListener.onTargetClick();
                    }
                });
    }
```
When I move on the second fragment and rotate the device I see this on the screen: 
![screenshot_1485854665](https://cloud.githubusercontent.com/assets/4811448/22459098/4b52085c-e7b0-11e6-93df-d2d1930c334d.png)

Can you fix it, please?

- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.7.0
**Stack trace:**
n/a
**Android version:**
api 24

**Comment by xiphirx** [comment]
This is not an issue with the library. You need to handle the state yourself. Similarly to #114 you need to be aware that -1 and +1 to your viewpager's current position will be initialized, so when you're in the second fragment, your first fragment is still alive. When you rotate the screen, your first fragment is also re-created, and since you dont have a method for determining if the tap target was displayed, it is shown again. You need to persist the state somehow and check it.
