### ISSUE TITLE
Toolbar icons disappear - further info

### ISSUE THREAD

**Issue by Rainer-Lang** [KeepSafe/TapTargetView#179]
Please have a look here at my comments at the end. Maybe they help...
https://github.com/KeepSafe/TapTargetView/issues/148

**Comment by xiphirx** [comment]
If you fixed the issue by changing `transparentTarget` to false, then that means the overlaying view is still drawing even thought it was dismissed, which is a bit hard to believe since the library explicitly removes itself from the view hierarchy when dismissed. 

Can you try to set your options back such that your icons seemingly disappear, and then trying to explicitly remove the `TapTargetView` instance?

**Comment by Rainer-Lang** [comment]
@xiphirx I can't explain it - but now it's working. The Icon stays visible in the toolbar while swiping in viewpager.
"Dismiss" was never the problem, it was "cancel".

@EuMenezes Could you please test it too?

For me it's solved. Don't know why..... strange....

**Comment by xiphirx** [comment]
Glad it worked out for you in the end. Closing until new information is available.
