### ISSUE TITLE
descriptionTextColor issue

### ISSUE THREAD

**Issue by andrey-kaiser** [KeepSafe/TapTargetView#194]
First of all, thanks for an awesome library!

Is is possible to set exact `descriptionTextColor`? In my case, both `titleTextColor` and `descriptionTextColor` are set to White, but description color definitely looks different. It looks like some color filter applied to it, but I need exactly white color.

I'm using latest library version. Thanks in advance!

**Comment by xiphirx** [comment]
It has some alpha applied to it, per the material design guidelines. That is what you're seeing.

**Comment by andrey-kaiser** [comment]
Thanks for reply! It would be cool to be able to adjust this alpha...
Should I close the issue? Or you can mark it with enhancement label as a reminder if you plan to add the feature.

**Comment by xiphirx** [comment]
I'm not sure at the moment... Unfortunately it seems like the current API is not flexible enough to fix certain issues with the library. There also needs to be a clear line of feature requests that will be honored. Currently I've been trying to adhere to material design guidelines as closely as possible which is why I would be hesitant to allow an API change like this, however, the guidelines do not explicitly say anything about the  description text alpha. The current behavior was just gleaned from the videos/screenshots that they provide and the more I think about it, I'm not sure that is a strong enough argument to restrict customization.

**Comment by Shashank58** [comment]
I would be willing to add this if required

**Comment by cristan** [comment]
You can make the text opaque by calling `descriptionTextAlpha(1f)`
