### ISSUE TITLE
Outer circle doesn't span fullscreen to match material spec

### ISSUE THREAD

**Issue by elisemurray** [KeepSafe/TapTargetView#196]
Problem: The sample screenshots in both the material design guidelines & the README show the outer circle spanning further than the width of the device. However using v1.9.1, the outer circle only spans a fraction of the device's width (screenshots below).

Expected: The outer radius should match the README screenshot and span greater than the width of the device.

- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:** 1.9.1

**Android version:** 7.1.2

**Screenshots**
Current version:
![outer_circle_mismatch](https://user-images.githubusercontent.com/556051/29534459-23757058-8684-11e7-8f6d-a52974affefe.png)

Readme version:
![readme_version](https://user-images.githubusercontent.com/556051/29534495-3a4e53bc-8684-11e7-8b26-ea50a321c16a.png)

Material spec:
![useredu_er_featuredisc_design_01](https://user-images.githubusercontent.com/556051/29534504-3fd68fb6-8684-11e7-9e0f-ebbdc5dc8af5.png)

**Comment by xiphirx** [comment]
This is simply because a Pixel has a screen size. The material design guidelines do not say it should span the entire width of the screen, only that the outer circle is centered on the target if it is within 88dp of the top or bottom. The screenshots provided there show that the text width is limited to 360dp, which is what is happening here. The Pixel's screen width is 411dp, so it will not span the entire width.
