### ISSUE TITLE
TapTarget onReady makes no sense and is broken

### ISSUE THREAD

**Issue by ricard-v** [KeepSafe/TapTargetView#323]
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used:**
1.12.0
**Stack trace:**
java.lang.IllegalArgumentException: Given null view to target
        at com.getkeepsafe.taptargetview.ViewTapTarget.<init>(ViewTapTarget.java:31)
        at com.getkeepsafe.taptargetview.ToolbarTapTarget.<init>(ToolbarTapTarget.java:36)
        at com.getkeepsafe.taptargetview.TapTarget.forToolbarMenuItem(TapTarget.java:153)
**Android version:**
Android 8.0

The stack trace and the Android version matters not as this issue is easy to see.

The `TapTarget` class exposes a method called `onReady(Runnable runnable)` which documentation says:

> In case your target needs time to be ready (laid out in your view, not created, etc), the
> runnable passed here will be invoked when the target is ready.

Since I had the problem on display some TapTargerViews because the views were not laid out, I thought I should use this method.

But the source code is as followed:
https://github.com/KeepSafe/TapTargetView/blob/4af5fe18ae2ff1657f4a200e447c2bddfe6490d4/taptargetview/src/main/java/com/getkeepsafe/taptargetview/TapTarget.java#L432-L438

Why would the `runnable` be immediately executed ? Where does it wait / check for the target view to be laid out?

In the stack trace, in the end, I am dealing with a `ViewTapTarget` which inherits from `TapTarget`. That class is **package-private** as well as `ToolbarTapTarget`. And in any case, the `ViewTapTarget#onReady` methods does perform code to wait for the view to be laid out using an internal `ViewUtil#onLaidOut` static method. That `ViewUtil` class and all its methods are also **package-private**.

So In any case, the following code throws the following exception: `java.lang.IllegalArgumentException: Given null view to target`:

I am on a Fragment, by the way.

```
TapTarget target = TapTarget.forToolbarMenuItem(
(Toolbar) getActivity().findViewById(R.id.toolbar), 
R.id.action_search, "Test", "test desc");
target.onReady(() -> {
        TapTargetView.showFor(getActivity(), target, new TapTargetView.Listener() {
            //...
        });
});
```

This code snippet is being called from the `onCreateOptionsMenu` method.

So in the end, why the `TapTarget#onReady` method does not perform the code to wait for the view to be laid out? An any of the available code to actually wait for a view to be laid out is completely inaccessible: I have to write it myself and that kind of defeat the purpouse, right?

Thank you for your help!

**Comment by xiphirx** [comment]
`TapTarget` is a fully generic target. It does not necessary mean its targeting a view, thats what `ViewTapTarget` is for. 

Since its a fully generic class, there is nothing to wait for in `onReady`, like `ViewTapTarget`.

If you need to wait for your view to be laid out then you should be using a `ViewTapTarget`. If you need more custom logic for your `onReady` function then you can subclass `ViewTapTarget`.

In terms of the code to wait for the view to be laid out, the implementation is not a public API because I do not want to take on the maintenance of it being a public API. Those utility functions aren't in the scope of what the library should be doing for you, so I do not want the risk of code depending on the functions where they're really only supposed to be used by the library's internal implementation.

You're always welcome to copy the utility functions, though.
