### ISSUE TITLE
Tint floating action button

### ISSUE THREAD

**Issue by mac229** [KeepSafe/TapTargetView#73]
There is no possibility to tint floating action button and set icon color or drawable.
I got all button in the tint color without any icon

**Comment by xiphirx** [comment]
The tint is simply a color overlay, and should only be used for simple opaque icons.

The FAB cannot be tinted using this method because the icon within it is covered by the color overlay. 

The guidelines omit examples of the FAB being tinted, so I'm not inclined to support this. Additionally, supporting something like this is non-trivial and will likely degrade performance due to color blending calculations.
